# Generated by Django 2.2.2 on 2019-06-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tut_title', models.CharField(max_length=200)),
                ('tut_content', models.TextField()),
                ('tut_publish', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
