# Generated by Django 2.2.2 on 2019-06-28 18:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190628_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tut',
            name='tut_publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 23, 51, 33, 49853), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tut',
            name='tut_ser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Series', verbose_name='Series'),
        ),
    ]
