# Generated by Django 2.2.2 on 2019-06-28 18:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190628_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='tut_cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Cat', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='tut',
            name='tut_publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 23, 56, 15, 413369), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tut',
            name='tut_ser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Series', verbose_name='Series'),
        ),
    ]
