# Generated by Django 2.2.2 on 2019-06-28 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190628_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tut',
            name='tut_publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 28, 23, 56, 19, 823385), verbose_name='date published'),
        ),
    ]
