# Generated by Django 2.2.2 on 2019-06-28 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190629_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tut',
            name='tut_publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 0, 2, 52, 965043), verbose_name='date published'),
        ),
    ]
