# Generated by Django 2.2.2 on 2019-06-28 18:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190629_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='tut_cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Cat', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='tut',
            name='tut_publish',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 29, 0, 13, 33, 123828), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tut',
            name='tut_ser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='main.Series', verbose_name='Series'),
        ),
    ]
